### ISSUE TITLE
Missing modules, kernel sources, and headers

### ISSUE THREAD

**Issue by akhepcat** [mrfixit2001/updates_repo#1]
There are no links for kernel sources, headers, or other modules;  this make further development of the system impossible to use with your update system.

For instance, I can't install wireguard, because there's no headers for compiling the module.
Also, I can't use iptables/ip6tables  because there are no netfilter/ipt  modules.

Please provide obvious links to the source so we can generate our own, or have them as separate (optional) downloads from the update script so that the full, complete system is available.

Thanks!

**Comment by mrfixit2001** [comment]
Thanks for asking! All the sources are in the other repos in this github account.
Kernel (and therefore kernel headers): https://github.com/mrfixit2001/rockchip-kernel
U-Boot: https://github.com/mrfixit2001/rockchip-u-boot

**Comment by mrfixit2001** [comment]
Additional note: all updates for the update script are available in this repo under a branch for that update version

**Comment by akhepcat** [comment]
Hi -  I see you've closed this, however the repo for the kernel doesn't provide the dot-config file for how the kernel is configured, nor the system.map or Module.symvers.

Those files are critical for doing follow-up module-building on the running kernel.
Can you please provide at least those three files in the filesystem repo?

Thanks

**Comment by mrfixit2001** [comment]
The files you are asking about are all generated at the time the kernel is compiled. They are not static or stored elsewhere. When you build the full kernel from source, those files should all be created. There is no additional source for the kernel, header, or modules compilation outside of what is in my kernel repo.

**Comment by akhepcat** [comment]
Yes -  and what's great about *you* supplying them with your build image is that other people then don't need to perform a full rebuild of the kernel just to generate additional modules.  They can simply use the module build system to generate modules that work with the image.

As it stands, there's not even a .config file  as a base for recompiling the entire kernel, leaving people wondering what default options to use.

**Comment by digitalsanity** [comment]
@akhepcat try:

zcat /proc/config.gz >.config

**Comment by mrfixit2001** [comment]
Just some additional info: the default configs are in /arch/arm64/configs, named rk3328_linux_defconfig and rk3399_linux_defconfig. These are the base for all my compiles.
